In [1]:
from google.colab import files
uploaded = files.upload()

Saving cleaned_preprocessed_disaster_data.csv to cleaned_preprocessed_disaster_data (1).csv

In [2]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

In [3]:
df=pd.read_csv('cleaned_preprocessed_disaster_data.csv')

In [4]:
df.head()

,iso3,country,disaster_type,year,deaths,affected,mng_cap,inventory,distance,priority_tier
0,BRA,Brazil,Flood,2018,4.0,250.0,4.247241,1664,120,Moderate
1,USA,United States of America,Wildfire,2002,0.0,1572.0,7.704286,1817,218,Low
2,RWA,Rwanda,Flood,2022,3.0,0.0,6.391964,662,448,Moderate
3,USA,United States of America,Drought,2024,0.0,0.0,5.591951,211,187,Critical
4,IDN,Indonesia,Road,2022,10.0,20.0,2.936112,705,434,Critical

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16752 entries, 0 to 16751
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   iso3           16752 non-null  object
 1   country        16752 non-null  object
 2   disaster_type  16752 non-null  object
 3   year           16752 non-null  int64
 4   deaths         16752 non-null  float64
 5   affected       16752 non-null  float64
 6   mng_cap        16752 non-null  float64
 7   inventory      16752 non-null  int64
 8   distance       16752 non-null  int64
 9   priority_tier  16752 non-null  object
dtypes: float64(3), int64(3), object(4)
memory usage: 1.3+ MB

In [6]:
df.describe()

,year,deaths,affected,mng_cap,inventory,distance
count,16752.000000,16752.000000,1.675200e+04,16752.000000,16752.000000,16752.000000
mean,2011.551457,112.176158,2.906085e+05,4.981133,1280.336497,303.878701
std,7.691874,2697.150605,4.466346e+06,1.732363,710.066894,169.658532
min,2000.000000,0.000000,0.000000e+00,2.000070,50.000000,10.000000
25%,2005.000000,2.000000,0.000000e+00,3.480829,663.000000,158.000000
50%,2011.000000,12.000000,1.235000e+02,4.968174,1284.000000,302.000000
75%,2018.000000,26.000000,6.580500e+03,6.490164,1898.000000,449.000000
max,2026.000000,222570.000000,3.300000e+08,7.999549,2499.000000,599.000000

In [7]:
df.isnull().sum()

iso3             0
country          0
disaster_type    0
year             0
deaths           0
affected         0
mng_cap          0
inventory        0
distance         0
priority_tier    0
dtype: int64

In [9]:
df = df.drop_duplicates()

In [10]:
labenc = LabelEncoder()

df['country'] = labenc.fit_transform(df['country'])
df['disaster_type'] = labenc.fit_transform(df['disaster_type'])
df['iso3'] = labenc.fit_transform(df['iso3'])
df['priority_tier'] = labenc.fit_transform(df['priority_tier'])

In [11]:
scaler = StandardScaler()

numerical_cols = ['deaths','affected','mng_cap','inventory','distance','year']

df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

In [12]:
X = df.drop('priority_tier', axis=1)
y = df['priority_tier']

,iso3,country,disaster_type,year,deaths,affected,mng_cap,inventory,distance,priority_tier
0,28,26,13,0.838383,-0.040109,-0.065012,-0.423649,0.540336,-1.083849,2
1,209,213,30,-1.241796,-0.041592,-0.064716,1.571977,0.755815,-0.506201,1
2,168,162,13,1.358428,-0.040480,-0.065068,0.814421,-0.870840,0.849504,2
3,209,213,5,1.618450,-0.041592,-0.065068,0.352603,-1.506011,-0.688926,0
4,87,91,26,1.358428,-0.037884,-0.065064,-1.180516,-0.810281,0.766983,0

In [22]:
y.value_counts()

priority_tier
2    5584
1    5584
0    5584
Name: count, dtype: int64

In [13]:
df.to_csv("final_cleaned_dataset.csv", index=False)

In [23]:
files.download("final_cleaned_dataset.csv")